[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lumina-tools"
version = "0.1.8"
authors = [
  { name="Ata Can Yaymacı", email="atacanymc@gmail.com" },
]
description = "Lithophane & Spiral Betty Generator"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Multimedia :: Graphics :: 3D Modeling",
]
keywords = ["lithophane", "3d-printing", "spiral-betty", "stl", "maker", "gift"]
dependencies = [
    "numpy>=1.20.0",
    "opencv-python>=4.5.0",
    "numpy-stl>=2.16.0",
    "click>=8.0.0"
]

[project.urls]
"Homepage" = "https://github.com/AtaCanYmc/lumina"
"Bug Tracker" = "https://github.com/AtaCanYmc/lumina/issues"

[project.scripts]
lumina = "lumina.cli:main"

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[tool.isort]
profile = "black"
line_length = 120
